service: aws-open-graph-image-generator
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  timeout: 10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*

functions:
  openGraphImageGenerator:
    handler: index.handler
    events:
      - httpApi: '*'
